### PR TITLE
Support for .NET Standard (multiple target frameworks)

### PR DESCRIPTION
**Pull request by Zaczero**
* Regenerated project file using Visual Studio 2019
* Added multiple target frameworks (compile both net framework 4.5.2 and net standard 2.0 at once)
* Removed SequencePoints="Release" from FodyWeavers (default value is Debug and should stay like that) [Read more here](https://github.com/ltrzesniewski/InlineIL.Fody#configuration)
* Updated readme file so it is valid for the current pull request
* Added missing fody license in license section

### CODE REVIEW

**Comment by michel-pi** [comment]
Hey,
i will merge your changes in 1 or 2 days.

> Removed SequencePoints="Release" from FodyWeavers (default value is Debug and should stay like that) Read more here

Can you explain why i should not change it to Release? If it does say that somewhere than i did not find it.
I am just curious

**Comment by Zaczero** [comment]
You can revert that change.
After I read the definition for the sequence points in manual I thought that it defined the compilation mode in which they are added. So if compiled in Release there would be sequence points added. Looks I had to misunderstood the definition. It is just a bit unclear.

**Comment by ltrzesniewski** [comment]
> I thought that it defined the compilation mode in which they are added.

That's exactly what this option does, and yes, it should stay at its default `Debug` value unless you have a *very* good reason to change it. Setting it to `Release` gets you a worse debugging experience in Debug mode, and *potentially* worse JIT codegen in Release mode. That's not exactly what you're after I suppose. 😉

I'll add some kind of *"do not change unless you know what you're doing"* warning to the InlineIL readme.

**Comment by Zaczero** [comment]
@michel-pi @ltrzesniewski Thanks for clarifying 😀

**Pull request merged**
